# Streamlit Secrets
# Updated with provided credentials

THINGSPEAK_CHANNEL_ID = "3254741"
THINGSPEAK_READ_KEY = "MWO5EB4I47OZCI4W"

TWILIO_ACCOUNT_SID = "AC3d305967e3e0b493a29623a00409c805"
TWILIO_AUTH_TOKEN = "1a024b986fa1d3f2f4d821fa21d325b1"
TWILIO_FROM_NUMBER = "+14155238886"
TWILIO_TO_NUMBER = "+916374930315"
